AllCops:
  Exclude:
    - '*/pkg/**/*'
    - 'integration-tests/apps/**/*'

Lint/HandleExceptions:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/Void:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundBody:
  Enabled: false

Style/Encoding:
  EnforcedStyle: when_needed

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 6

Style/PercentQLiterals:
  EnforcedStyle: upper_case_q

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/UnneededCapitalW:
  Enabled: false
