language: ruby

rvm:
  - jruby-19mode

jdk:
  - openjdk7
  - oraclejdk7

env: DEBUG=true

install: bundle install

before_script: bundle exec rake build

script:
  - bundle exec rake rubocop
  - bundle exec rake spec
  - cd integration-tests && bundle exec rake spec:all

branches:
  only:
    - torqbox
