language: ruby

rvm:
  - jruby-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head

jdk:
  - openjdk7

sudo: false

# cache:
#   directories:
#     - $HOME/.m2/repository

install: travis_retry bundle install

before_script:
  - unset RACK_ENV RAILS_ENV
  - bundle exec rake build

script:
  - bundle exec rake rubocop
  - bundle exec rake spec
  - cd integration-tests
  - travis_wait bundle exec rake spec:wildfly:setup
  - bundle exec rake spec:all

branches:
  only:
    - master
